tag: user.diagram_drawing
-
<user.diagram_drawing_position_specifier> and <user.diagram_drawing_position_specifier> quad <user.diagram_drawing_number_float>: 
    user.draw_quadratic_between_named_positions_with_slope(diagram_drawing_position_specifier_1, diagram_drawing_position_specifier_2, diagram_drawing_number_float)
<user.diagram_drawing_position_specifier> and <user.diagram_drawing_position_specifier> dash quad <user.diagram_drawing_number_float>: 
    user.draw_dashed_quadratic_between_stored_positions_with_slope(diagram_drawing_position_specifier_1, diagram_drawing_position_specifier_2, diagram_drawing_number_float)
<user.diagram_drawing_position_specifier> and <user.diagram_drawing_position_specifier> curve <user.diagram_drawing_number_float> slope <user.diagram_drawing_number_float>: 
    user.diagram_drawing_draw_two_slope_curve(diagram_drawing_position_specifier_1, diagram_drawing_position_specifier_2, diagram_drawing_number_float_1, diagram_drawing_number_float_2)
